namespace: secrets-operator
helmCharts:
  - name: secrets-operator
    namespace: secrets-operator
    releaseName: secrets-operator
    includeCRDs: true
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    version: 0.6.5