services:

  nginx:
    image: nginx:latest
    container_name: nginx-loki
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - loki

  loki:
    container_name: grafana-loki
    restart: unless-stopped
    image: grafana/loki:latest
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - "3100:3100"
    volumes:1
      - /mnt/loki/:/mnt/
      - ./complete-local-config.yaml:/etc/loki/complete-local-config.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: -config.file=/etc/loki/complete-local-config.yaml -config.expand-env=true