apiVersion: 1

datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "http://prometheus:9090"
    basicAuth: false
    isDefault: true
    editable: true

  - name: "Loki"
    type: "loki"
    url: "https://your_loki_domain"
    isDefault: false
    jsonData:
      maxLines: 1000

  - name: "Kube Prometheus"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "https://your_kube_metrics_domain"
    basicAuth: false
    editable: true